[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@sentry/netlify-build-plugin"
  
  [plugins.inputs]
    sentryOrg = "tacticmedia"
    sentryProject = "thesportswriter-com-au"