[build]
  publish = "dist"
  command = "npm run export"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "@sentry/netlify-build-plugin"
  
  [plugins.inputs]
    sentryOrg = "tacticmedia"
    sentryProject = "thesportswriter-com-au"